[package]
name = "bendctl"
version = "0.1.0"
description = "All-in-one tool for setting up, managing with Databend"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "bendctl"
path = "src/bin/bendctl.rs"

[features]

[dependencies]
# Workspace dependencies
databend-query = { path = "../query" }
common-base = { path = "../common/base" }
common-datavalues = { path = "../common/datavalues" }
common-tracing = { path = "../common/tracing" }

itertools = "0.10.3"
databend-meta = { path = "../metasrv" }
common-meta-raft-store = { path = "../common/meta/raft-store" }
colored = "2.0.0"
comfy-table = "5.0.0"
dirs = "4.0.0"
clap = { version = "3.0.0-rc.7", features = ["env"] }
clap_generate = "3.0.0-rc.7"
dyn-clone = "1.0.4"
flate2 = "1.0.22"
handlebars = "4.1.6"
indicatif = "0.16.2"
run_script = "0.9.0"
rustyline = "9.1.2"
futures = "0.3.18"
byte-unit = "4.0.13"
num-format = "0.4.0"
fs_extra = "1.2.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
sha2 = "0.10.0"
sysinfo = "0.21.2"
tar = "0.4.38"
thiserror = "1.0.30"
ureq = { version = "2.3.1", features = ["json"] }
nix = "0.23.1"
serde_yaml = "0.8.21"
portpicker = "0.1.1"
reqwest = { version = "0.11.8", features = ["json", "native-tls", "multipart", "blocking", "tokio-rustls", "stream"] }
libc = "0.2.109"
lexical-util = "0.8.1"
async-trait = "0.1.52"
webbrowser = "0.5.5"
async-std = "1.10.0"
tryhard = "0.4.0"
tokio-util = "0.6.9"
csv = "1.1.6"
http = "0.2.5"

[dev-dependencies]
tempfile = "3.2.0"
assert_cmd = "2.0.2"
predicates = "2.1.0"
httpmock = "0.6.4"

[build-dependencies]
common-building = { path = "../common/building" }
