name: Auto tag for nightly release

on:
  schedule:
    # Release at 00:00 UTC+8
    - cron:  '0 16 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Bump version and push tag
        uses: actions/github-script@v6
        with:
          script: |
            let tag = ${{ steps.get-latest-tag.outputs.tag }};
            let patch = /v(\d+)\.(\d+).(\d+)-nightly/g.exec(tag)[3];
            let next_patch = parseInt(patch) + 1;
            let next_tag = tag.replace(patch+"-nightly", next_patch+"-nightly");
            github.octokit.rest.git.createRef({
              context.repo.owner,
              context.repo.repo,
              "refs/tags/"+next_tag,
              context.sha,
            });
